### ISSUE TITLE
org.apache.log4j.Level

### ISSUE THREAD

**Issue by afghifariii** [timveil/hive-jdbc-uber-jar#10]
I got this following error when using version 2.6.2.0-205 in DataGrip.

```
java.lang.ClassNotFoundException: org.apache.log4j.Level
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:290)
	at org.apache.hive.jdbc.HiveConnection.<clinit>(HiveConnection.java:111)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
	at com.intellij.database.remote.jdbc.impl.RemoteDriverImpl.connect(RemoteDriverImpl.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745) (no stack trace).
java.lang.NoClassDefFoundError: org/apache/log4j/Level

```
When i try to use 2.6.1.0-129, test connection was successful but it said "method not supported" maybe because i'm using HDP 2.6.2.0-205

**Comment by Sammers21** [comment]
have the same issue

**Comment by timveil** [comment]
resolved issue; please download the latest binaries

**Comment by Sammers21** [comment]
@timveil, I have the problem when using latest release

**Comment by Sammers21** [comment]
@timveil, or you mean the one you have just released?

**Comment by timveil** [comment]
@Sammers21 please try the release i just uploaded within the last hour or so.  i believe i've addressed the CNF exception

**Comment by timveil** [comment]
@Sammers21 

see: https://github.com/timveil/hive-jdbc-uber-jar/releases/tag/v1.7-2.6.2
